modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "createbrewery"
version = "${mod_version}"
displayName = "Create Brewery"
description = "Realistic, fully automatable beer production built on Create."

[[dependencies.createbrewery]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.228,)"

[[dependencies.createbrewery]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"

[[dependencies.createbrewery]]
modId = "create"
type = "required"
versionRange = "[6.0.10,6.1.0)"
