package com.createbrewery;

import com.createbrewery.data.ModDataMaps;
import com.createbrewery.data.ModLootModifiers;
import com.createbrewery.data.ModRecipeProvider;
import com.simibubi.create.foundation.data.CreateRegistrate;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.config.ModConfig;

@Mod(CreateBrewery.MOD_ID)
public class CreateBrewery {
    public static final String MOD_ID = "createbrewery";
    public static final CreateRegistrate REGISTRATE = CreateRegistrate.create(MOD_ID)
        .defaultCreativeTab((net.minecraft.resources.ResourceKey<net.minecraft.world.item.CreativeModeTab>) null);

    public CreateBrewery(IEventBus modEventBus, ModContainer modContainer) {
        REGISTRATE.registerEventListeners(modEventBus);
        ModFluids.register();
        ModItems.register();
        ModBlocks.register();
        ModBlockEntities.register();
        ModCreativeTabs.register(modEventBus);
        com.createbrewery.effect.ModEffects.register(modEventBus);
        com.createbrewery.drugs.HallucinationEntity.register(modEventBus);
        com.createbrewery.entity.ModEntities.register(modEventBus);
        com.createbrewery.drugs.Purity.register(modEventBus);
        modEventBus.addListener((net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent event) ->
            event.enqueueWork(com.createbrewery.drugs.TanCompat::init));
        com.createbrewery.drunk.ModAttachments.register(modEventBus);
        com.createbrewery.particle.ModParticles.register(modEventBus);
        com.createbrewery.sound.ModSounds.register(modEventBus);
        // Optional: only filled when Tobacconery is installed, no dependency on it.
        REGISTRATE.addDataGenerator(com.tterrag.registrate.providers.ProviderType.ITEM_TAGS, tags -> tags.addTag(ModTags.JOINT_TOBACCO)
            .addOptional(net.minecraft.resources.ResourceLocation.fromNamespaceAndPath("tobacconery", "chopped_tobacco")));
        com.createbrewery.data.PlayerTextLang.register(REGISTRATE);
        REGISTRATE.addRawLang("itemGroup.createbrewery", "Create Brewery");
        REGISTRATE.addRawLang("effect.createbrewery.inebriation", "Inebriation");
        REGISTRATE.addRawLang("effect.createbrewery.hangover", "Severe Hangover");
        REGISTRATE.addRawLang("effect.createbrewery.hiccups", "Hiccups");
        REGISTRATE.addRawLang("effect.createbrewery.stumble", "Stumble");
        REGISTRATE.addRawLang("effect.createbrewery.delirium", "Delirium");
        REGISTRATE.addRawLang("effect.createbrewery.blackout", "Blackout");
        REGISTRATE.addRawLang("effect.createbrewery.alcohol_poisoning", "Alcohol Poisoning");
        REGISTRATE.addRawLang("effect.createbrewery.good_mood", "Good Mood");
        REGISTRATE.addRawLang("effect.createbrewery.cheers", "Cheers");
        REGISTRATE.addRawLang("effect.createbrewery.vomiting", "Vomiting");
        REGISTRATE.addRawLang("effect.createbrewery.painkiller", "Painkiller");
        REGISTRATE.addRawLang("effect.createbrewery.coke_high", "Coke High");
        REGISTRATE.addRawLang("effect.createbrewery.coke_crash", "Crash");
        REGISTRATE.addRawLang("effect.createbrewery.keta_high", "Ketamine High");
        REGISTRATE.addRawLang("effect.createbrewery.k_hole", "K-Hole");
        REGISTRATE.addRawLang("effect.createbrewery.dazed", "Dazed");
        REGISTRATE.addRawLang("effect.createbrewery.weed_high", "Stoned");
        REGISTRATE.addRawLang("effect.createbrewery.greening_out", "Greening Out");
        REGISTRATE.addRawLang("effect.createbrewery.lsd_trip", "LSD Trip");
        REGISTRATE.addRawLang("effect.createbrewery.shroom_trip", "Mushroom Trip");
        REGISTRATE.addRawLang("effect.createbrewery.mescaline_trip", "Mescaline Trip");
        REGISTRATE.addRawLang("effect.createbrewery.psy_tolerance", "Tolerance");
        REGISTRATE.addRawLang("effect.createbrewery.bad_trip", "Bad Trip");
        REGISTRATE.addRawLang("effect.createbrewery.afterglow", "Afterglow");
        REGISTRATE.addRawLang("effect.createbrewery.flashback", "Flashback");
        REGISTRATE.addRawLang("effect.createbrewery.flashback_pending", "Flashback Pending");
        REGISTRATE.addRawLang("effect.createbrewery.breakthrough", "Breakthrough");
        REGISTRATE.addRawLang("effect.createbrewery.rolling", "Rolling");
        REGISTRATE.addRawLang("effect.createbrewery.comedown", "Comedown");
        REGISTRATE.addRawLang("effect.createbrewery.tweak", "Tweaking");
        REGISTRATE.addRawLang("effect.createbrewery.meth_crash", "Meth Crash");
        REGISTRATE.addRawLang("effect.createbrewery.hyperthermia", "Hyperthermia");
        REGISTRATE.addRawLang("effect.createbrewery.psychosis", "Psychosis");
        REGISTRATE.addRawLang("effect.createbrewery.nod", "Nodding");
        REGISTRATE.addRawLang("effect.createbrewery.calm", "Sedated");
        REGISTRATE.addRawLang("effect.createbrewery.respiratory_depression", "Respiratory Depression");
        REGISTRATE.addRawLang("effect.createbrewery.withdrawal", "Withdrawal");
        REGISTRATE.addRawLang("effect.createbrewery.wah", "Nitrous High");
        REGISTRATE.addRawLang("effect.createbrewery.candyflip", "Candyflip");
        REGISTRATE.addRawLang("effect.createbrewery.speedball", "Speedball");
        REGISTRATE.addRawLang("effect.createbrewery.stoned_trip", "Stoned Trip");
        REGISTRATE.addRawLang("effect.createbrewery.nitrous_peak", "Nitrous Peak");
        REGISTRATE.addRawLang("effect.createbrewery.dehydrated", "Dehydrated");
        REGISTRATE.addRawLang("effect.createbrewery.naloxone", "Naloxone");
        REGISTRATE.addRawLang("item.createbrewery.naloxon.desc1", "Emergency nasal spray for opioid overdoses");
        REGISTRATE.addRawLang("item.createbrewery.naloxon.desc2", "Right-click on unconscious players or yourself");
        REGISTRATE.addRawLang("item.createbrewery.naloxon.desc3", "Triggers immediate withdrawal in opioid dependents");
        REGISTRATE.addRawLang("effect.createbrewery.opioid_habit", "Tolerance (Opioids)");
        REGISTRATE.addRawLang("effect.createbrewery.craving", "Craving");
        REGISTRATE.addRawLang("effect.createbrewery.weed_habit", "Tolerance (Weed)");
        REGISTRATE.addRawLang("effect.createbrewery.coke_habit", "Tolerance (Coke)");
        REGISTRATE.addRawLang("effect.createbrewery.meth_habit", "Tolerance (Crystal)");
        REGISTRATE.addRawLang("effect.createbrewery.seizure", "Seizure");
        REGISTRATE.addRawLang("effect.createbrewery.hyponatremia", "Water Intoxication");
        REGISTRATE.addRawLang("effect.createbrewery.numbness", "Numbness");
        REGISTRATE.addRawLang("effect.createbrewery.comedown_pending", "Comedown Pending");
        REGISTRATE.addRawLang("effect.createbrewery.cocaethylene", "Cocaethylene");
        REGISTRATE.addRawLang("effect.createbrewery.edible_pending", "Digesting");
        REGISTRATE.addRawLang("death.attack.createbrewery.keta_bladder", "%1$s did not survive ketamine bladder syndrome");
        REGISTRATE.addRawLang("death.attack.createbrewery.seizure", "%1$s had a seizure");
        REGISTRATE.addRawLang("death.attack.createbrewery.overdose", "%1$s stopped breathing");
        REGISTRATE.addRawLang("death.attack.createbrewery.hyperthermia", "%1$s danced themselves to death");
        REGISTRATE.addRawLang("death.attack.createbrewery.skin_picking", "%1$s scratched themselves bloody");
        REGISTRATE.addRawLang("subtitles.createbrewery.cough", "Coughing");
        REGISTRATE.addRawLang("subtitles.createbrewery.giggle", "Giggling");
        REGISTRATE.addRawLang("subtitles.createbrewery.co2", "CO2 jet roars");
        REGISTRATE.addRawLang("effect.createbrewery.ck_mix", "CK-Mix");
        REGISTRATE.addRawLang("effect.createbrewery.tachycardia", "Tachycardia");
        REGISTRATE.addRawLang("effect.createbrewery.cottonmouth", "Cottonmouth");
        REGISTRATE.addRawLang("effect.createbrewery.snack_bliss", "Munchies");
        REGISTRATE.addRawLang("effect.createbrewery.heart_attack", "Heart Attack");
        REGISTRATE.addRawLang("effect.createbrewery.aspiration", "Choking on Vomit");
        REGISTRATE.addRawLang("death.attack.createbrewery.aspiration", "%1$s choked on their own vomit");
        REGISTRATE.addRawLang("death.attack.createbrewery.nosebleed", "%1$s bled to death from a nosebleed");
        REGISTRATE.addRawLang("death.attack.createbrewery.heart_attack", "%1$s suffered a heart attack");
        REGISTRATE.addRawLang("subtitles.createbrewery.sniff", "Sniffling");
        REGISTRATE.addRawLang("death.attack.createbrewery.stomach_bleeding", "%1$s washed down ibuprofen with beer");
        REGISTRATE.addRawLang("death.attack.createbrewery.painkiller_overdose", "%1$s swallowed too many painkillers");
        REGISTRATE.addRawLang("subtitles.createbrewery.glass_clink", "Glasses clinking");
        REGISTRATE.addRawLang("subtitles.createbrewery.hiccup", "Hiccup");
        REGISTRATE.addRawLang("subtitles.createbrewery.heartbeat", "Heart thumping");
        REGISTRATE.addRawLang("subtitles.createbrewery.beer_open", "Beer hiss");
        REGISTRATE.addRawLang("subtitles.createbrewery.ear_ringing", "Tinnitus");
        REGISTRATE.addRawLang("subtitles.createbrewery.dj_scratch", "DJ scratches record");
        REGISTRATE.addRawLang("death.attack.createbrewery.alcohol_poisoning", "%1$s drank themselves to death");
        // Hand-written strings with no registry object of their own to hang a .lang() call
        // off of. addRawLang feeds the same RegistrateLangProvider as every other entry, so
        // this stays in the one generated en_us.json rather than a hand file that would
        // collide with it (that file is 100% datagen output already - see ModFluids, item(),
        // block()).
        REGISTRATE.addRawLang("createbrewery.goggles.fermenter.idle", "Idle");
        REGISTRATE.addRawLang("createbrewery.goggles.fermenter.progress", "Fermenting: %s%%");
        REGISTRATE.addRawLang("createbrewery.goggles.fermenter.remaining", "%s days remaining");
        REGISTRATE.addRawLang("createbrewery.recipe.fermenting", "Fermenting");
        REGISTRATE.addRawLang("createbrewery.jei.fermenting.one_day", "1 day");
        REGISTRATE.addRawLang("createbrewery.jei.fermenting.days", "%s days");
        REGISTRATE.addRawLang("createbrewery.jei.fermenting.days_decimal", "%s days");

        // Club Gadgets
        REGISTRATE.addRawLang("createbrewery.strobe.mode.beat", "Mode: Beat Sync (Kicks)");
        REGISTRATE.addRawLang("createbrewery.strobe.mode.strobe", "Mode: Fast Strobe (~7 Hz)");
        REGISTRATE.addRawLang("createbrewery.strobe.mode.redstone", "Mode: Redstone Signal");
        REGISTRATE.addRawLang("createbrewery.strobe.brightness.1", "Brightness: Soft (1/5)");
        REGISTRATE.addRawLang("createbrewery.strobe.brightness.2", "Brightness: Normal (2/5)");
        REGISTRATE.addRawLang("createbrewery.strobe.brightness.3", "Brightness: Bright (3/5)");
        REGISTRATE.addRawLang("createbrewery.strobe.brightness.4", "Brightness: Extreme (4/5)");
        REGISTRATE.addRawLang("createbrewery.strobe.brightness.5", "Brightness: BLINDING (5/5)");
        REGISTRATE.addRawLang("createbrewery.laser.color_changed", "Laser color updated!");
        REGISTRATE.addRawLang("createbrewery.laser.on", "Laser on");
        REGISTRATE.addRawLang("createbrewery.laser.off", "Laser off");
        REGISTRATE.addRawLang("createbrewery.laser.rainbow_mode", "Laser Mode: Rainbow Prism!");
        REGISTRATE.addRawLang("createbrewery.laser.pattern.beam", "Pattern: Scanner");
        REGISTRATE.addRawLang("createbrewery.laser.pattern.sweep", "Pattern: Swinging Fan");
        REGISTRATE.addRawLang("createbrewery.laser.pattern.fan", "Pattern: Spinning Fan");
        REGISTRATE.addRawLang("createbrewery.laser.pattern.burst", "Pattern: Beat Chase");
        REGISTRATE.addRawLang("createbrewery.laser.pattern.tunnel", "Pattern: Tunnel");
        REGISTRATE.addRawLang("createbrewery.fog_machine.filled", "Fog Machine filled (%s mB)");
        REGISTRATE.addRawLang("createbrewery.fog_machine.started", "Fog Machine started (%s mB remaining)");
        REGISTRATE.addRawLang("createbrewery.fog_machine.stopped", "Fog Machine stopped (%s mB remaining)");
        REGISTRATE.addRawLang("createbrewery.goggles.fog_machine.header", "Fog Machine");
        REGISTRATE.addRawLang("createbrewery.subwoofer.active", "Subwoofer: Bass active");
        REGISTRATE.addRawLang("createbrewery.subwoofer.inactive", "Subwoofer: Inactive");
        // The amp rack (AmpRackScreen, AmpStatus, the DJ mixer's status line).
        REGISTRATE.addRawLang("createbrewery.amp.tab.simple", "Simple");
        REGISTRATE.addRawLang("createbrewery.amp.tab.zones", "Zones");
        REGISTRATE.addRawLang("createbrewery.amp.tab.expert", "Expert");
        REGISTRATE.addRawLang("createbrewery.amp.power", "POWER");
        REGISTRATE.addRawLang("createbrewery.amp.power.tip", "Switches the whole sound system on and off. Off: speakers and subwoofers go quiet and the lights stop following the music; the DJ still hears the decks at the booth.");
        REGISTRATE.addRawLang("createbrewery.amp.master", "Master: %s dB");
        REGISTRATE.addRawLang("createbrewery.amp.master.tip", "Volume of the whole club. Turn it down when the light shows red.");
        REGISTRATE.addRawLang("createbrewery.amp.auto", "Auto Setup");
        REGISTRATE.addRawLang("createbrewery.amp.auto.tip", "Finds every linked speaker, sorts it into a zone and sets crossover, delays and levels. Press it whenever you build or change your club.");
        REGISTRATE.addRawLang("createbrewery.amp.setup_done", "Set up %s speakers and %s subwoofers (%s in side rooms, %s delay)");
        REGISTRATE.addRawLang("createbrewery.amp.preset.0", "Club");
        REGISTRATE.addRawLang("createbrewery.amp.preset.1", "Live");
        REGISTRATE.addRawLang("createbrewery.amp.preset.2", "Background");
        REGISTRATE.addRawLang("createbrewery.amp.preset.3", "Night");
        REGISTRATE.addRawLang("createbrewery.amp.preset.custom", "Custom settings - press a preset to go back");
        REGISTRATE.addRawLang("createbrewery.amp.preset.tip", "Ready-made sound: Club for dancing, Live for bands, Background for a bar, Night when it must be quiet. Moving any control afterwards makes it Custom.");
        REGISTRATE.addRawLang("createbrewery.amp.zone.0", "Dance floor");
        REGISTRATE.addRawLang("createbrewery.amp.zone.1", "Subwoofers");
        REGISTRATE.addRawLang("createbrewery.amp.zone.2", "Delay");
        REGISTRATE.addRawLang("createbrewery.amp.zone.3", "Side room");
        REGISTRATE.addRawLang("createbrewery.amp.zone.4", "DJ monitor");
        REGISTRATE.addRawLang("createbrewery.amp.zone.tip.0", "Speakers that face the dance floor.");
        REGISTRATE.addRawLang("createbrewery.amp.zone.tip.1", "The subwoofers: the deep bass you feel.");
        REGISTRATE.addRawLang("createbrewery.amp.zone.tip.2", "Speakers far at the back: they get a delay so they land in step with the front.");
        REGISTRATE.addRawLang("createbrewery.amp.zone.tip.3", "Speakers behind a wall, like the bar or the toilets: usually quieter.");
        REGISTRATE.addRawLang("createbrewery.amp.zone.tip.4", "What the DJ hears at the booth.");
        REGISTRATE.addRawLang("createbrewery.amp.zone_gain", "%s: %s");
        REGISTRATE.addRawLang("createbrewery.amp.off", "off");
        REGISTRATE.addRawLang("createbrewery.amp.none", "(no speakers)");
        REGISTRATE.addRawLang("createbrewery.amp.mute", "M");
        REGISTRATE.addRawLang("createbrewery.amp.mute.tip", "Mute: silences this zone");
        REGISTRATE.addRawLang("createbrewery.amp.low", "Bass: %s dB");
        REGISTRATE.addRawLang("createbrewery.amp.low.tip", "Turns the low end of this zone up or down.");
        REGISTRATE.addRawLang("createbrewery.amp.mid", "Mids: %s dB");
        REGISTRATE.addRawLang("createbrewery.amp.mid.tip", "Voices and most instruments.");
        REGISTRATE.addRawLang("createbrewery.amp.high", "Treble: %s dB");
        REGISTRATE.addRawLang("createbrewery.amp.high.tip", "Hi-hats and sparkle. Turn it down if it hurts.");
        REGISTRATE.addRawLang("createbrewery.amp.hpf", "Low cut: %s");
        REGISTRATE.addRawLang("createbrewery.amp.hpf.tip", "Cuts everything below this frequency. Keeps subwoofers clean (30-40 Hz) and small speakers from booming.");
        REGISTRATE.addRawLang("createbrewery.amp.hz", "%s Hz");
        REGISTRATE.addRawLang("createbrewery.amp.delay", "Delay: %s ms (%s blocks)");
        REGISTRATE.addRawLang("createbrewery.amp.delay.tip", "Holds this zone back. Sound travels about one block in 3 ms.");
        REGISTRATE.addRawLang("createbrewery.amp.limit_at", "Limiter: %s dB");
        REGISTRATE.addRawLang("createbrewery.amp.limit.tip", "The loudest this zone may get. Lower protects ears in side rooms.");
        REGISTRATE.addRawLang("createbrewery.amp.invert", "Polarity: %s");
        REGISTRATE.addRawLang("createbrewery.amp.invert.on", "inverted");
        REGISTRATE.addRawLang("createbrewery.amp.invert.off", "normal");
        REGISTRATE.addRawLang("createbrewery.amp.invert.tip", "Flips the speaker cone. Try it if the bass gets thinner where two zones meet.");
        REGISTRATE.addRawLang("createbrewery.amp.crossover", "Crossover: %s Hz");
        REGISTRATE.addRawLang("createbrewery.amp.crossover.tip", "Below this the subwoofers play, above it the speakers.");
        REGISTRATE.addRawLang("createbrewery.amp.slope", "Slope: %s");
        REGISTRATE.addRawLang("createbrewery.amp.slope.0", "24 dB/oct");
        REGISTRATE.addRawLang("createbrewery.amp.slope.1", "48 dB/oct");
        REGISTRATE.addRawLang("createbrewery.amp.slope.tip", "How sharply subs and speakers are split. 48 is tighter.");
        REGISTRATE.addRawLang("createbrewery.amp.align", "Alignment: %s");
        REGISTRATE.addRawLang("createbrewery.amp.align.tip", "Sound takes time through the air: far speakers are delayed so everything arrives together.");
        REGISTRATE.addRawLang("createbrewery.amp.system", "Whole system");
        REGISTRATE.addRawLang("createbrewery.amp.reset_hint", "Right-click a control to reset it");
        REGISTRATE.addRawLang("createbrewery.amp.readonly", "Another amp rack drives this booth (%s %s %s)");
        REGISTRATE.addRawLang("createbrewery.amp.row", "%s blocks %s");
        REGISTRATE.addRawLang("createbrewery.amp.dir.north", "north");
        REGISTRATE.addRawLang("createbrewery.amp.dir.south", "south");
        REGISTRATE.addRawLang("createbrewery.amp.dir.east", "east");
        REGISTRATE.addRawLang("createbrewery.amp.dir.west", "west");
        REGISTRATE.addRawLang("createbrewery.amp.zones.auto", "A");
        REGISTRATE.addRawLang("createbrewery.amp.zones.tip", "Click the zone to move this speaker. A = sorted automatically.");
        REGISTRATE.addRawLang("createbrewery.amp.zones.empty", "No speakers linked yet");
        REGISTRATE.addRawLang("createbrewery.amp.zones.subs", "%s subwoofers (always in Subwoofers)");
        REGISTRATE.addRawLang("createbrewery.amp.limit", "LIMIT -%s dB");
        REGISTRATE.addRawLang("createbrewery.amp.status.unlinked", "Not linked: right-click the DJ booth with the rack in hand");
        REGISTRATE.addRawLang("createbrewery.amp.status.other_rack", "Another rack drives this booth");
        REGISTRATE.addRawLang("createbrewery.amp.status.power_off", "Power is off: press POWER");
        REGISTRATE.addRawLang("createbrewery.amp.status.too_loud", "Too loud! Turn MASTER down");
        REGISTRATE.addRawLang("createbrewery.amp.status.at_limit", "At the limit: a little quieter");
        REGISTRATE.addRawLang("createbrewery.amp.status.no_speakers", "No speakers linked: right-click the booth with speakers in hand");
        REGISTRATE.addRawLang("createbrewery.amp.status.no_subs", "No subwoofers on: the bass comes from the speakers");
        REGISTRATE.addRawLang("createbrewery.amp.status.muted", "Zone %s is muted");
        REGISTRATE.addRawLang("createbrewery.amp.status.ok", "All good");
        REGISTRATE.addRawLang("createbrewery.mic.on", "Microphone on: talk into it with Simple Voice Chat");
        REGISTRATE.addRawLang("createbrewery.mic.off", "Microphone off");
        REGISTRATE.addRawLang("createbrewery.mic.unlinked", "Not linked - right-click the DJ booth with it in hand");
        REGISTRATE.addRawLang("createbrewery.dmx.record", "REC");
        REGISTRATE.addRawLang("createbrewery.dmx.record_hint", "Timecode: records your moves to the song playing on the nearest DJ booth, and plays them back whenever that record plays. Shift-click forgets this song's show");
        REGISTRATE.addRawLang("createbrewery.dmx.cues", "%s cues");
        REGISTRATE.addRawLang("createbrewery.dmx.no_booth", "No DJ booth within 16 blocks to record to");
        REGISTRATE.addRawLang("createbrewery.hazer.on", "Hazer on: the haze builds up over half a minute");
        REGISTRATE.addRawLang("createbrewery.hazer.off", "Hazer off: the haze clears within a minute");
        REGISTRATE.addRawLang("createbrewery.cold_spark.auto_on", "Cold sparks: fire at the drops");
        REGISTRATE.addRawLang("createbrewery.cold_spark.auto_off", "Cold sparks: redstone only");
        REGISTRATE.addRawLang("createbrewery.cold_spark.height", "Fountain height: %s blocks");
        REGISTRATE.addRawLang("createbrewery.subwoofer.unlinked", "Subwoofer on, but not linked - right-click the DJ booth with subwoofers in hand");
        REGISTRATE.addRawLang("createbrewery.dj.beat_drop", "DROP TRIGGERED!");
        REGISTRATE.addRawLang("createbrewery.dj.deck_inserted", "%s: %s loaded");
        REGISTRATE.addRawLang("createbrewery.dj.playing", "▶ Playing %s: %s");
        REGISTRATE.addRawLang("createbrewery.dj.deck_empty", "%s is empty!");
        REGISTRATE.addRawLang("createbrewery.dj.decks_full", "Both decks full! (Shift+Right-click to eject)");
        REGISTRATE.addRawLang("createbrewery.dj.ejected", "Discs ejected");
        REGISTRATE.addRawLang("createbrewery.dj.eq_high", "HI");
        REGISTRATE.addRawLang("createbrewery.dj.eq_high.hint", "Highs (hats, vocals): left kills them, middle is flat");
        REGISTRATE.addRawLang("createbrewery.dj.eq_mid", "MID");
        REGISTRATE.addRawLang("createbrewery.dj.eq_mid.hint", "Mids (synths, snares): left kills them, middle is flat");
        REGISTRATE.addRawLang("createbrewery.dj.eq_low", "LOW");
        REGISTRATE.addRawLang("createbrewery.dj.eq_low.hint", "Bass (kick, bassline): left kills it - swap basslines between decks");
        REGISTRATE.addRawLang("createbrewery.dj.filter", "FLT");
        REGISTRATE.addRawLang("createbrewery.dj.filter.hint", "Filter: left sweeps a low-pass down, right a high-pass up; double-click for off");
        REGISTRATE.addRawLang("createbrewery.dj.fx_amount", "FX");
        REGISTRATE.addRawLang("createbrewery.dj.fx_amount.hint", "How much goes into the effect; turn it down and the tail rings out");
        REGISTRATE.addRawLang("createbrewery.dj.fx.none", "FX: off");
        REGISTRATE.addRawLang("createbrewery.dj.fx.echo", "FX: Echo 1/2");
        REGISTRATE.addRawLang("createbrewery.dj.fx.reverb", "FX: Reverb");
        REGISTRATE.addRawLang("createbrewery.dj.cue", "CUE");
        REGISTRATE.addRawLang("createbrewery.dj.cue_hint", "Headphones: hear this deck yourself, whatever the crossfader says (at the booth only)");
        REGISTRATE.addRawLang("createbrewery.dj.loop_hint", "Loop this many beats; the song runs on underneath (slip). Again to let go");
        REGISTRATE.addRawLang("createbrewery.dj.knob_narration", "%s: %s percent");
        REGISTRATE.addRawLang("createbrewery.speaker.linked", "Linked to this DJ booth - place them around your club");
        REGISTRATE.addRawLang("createbrewery.speaker.relinked", "Speaker linked to the DJ booth");
        REGISTRATE.addRawLang("createbrewery.speaker.too_far", "No DJ booth there, or more than %s blocks away");
        REGISTRATE.addRawLang("createbrewery.speaker.unlinked", "Not linked - right-click a DJ booth with speakers in hand");
        REGISTRATE.addRawLang("createbrewery.speaker.status", "Plays the DJ booth at %s, %s, %s");
        REGISTRATE.addRawLang("createbrewery.speaker.lore", "Linked to DJ booth at %s, %s, %s");
        REGISTRATE.addRawLang("item.createbrewery.hemp_seeds.hint", "On hydrated farmland under high light (sun or lamps). Half turn out male: remove them early before they pollinate females.");
        REGISTRATE.addRawLang("item.createbrewery.coca_seedling.hint", "Only grows in jungles, slowly: takes about 4 days to harvest.");
        REGISTRATE.addRawLang("item.createbrewery.mushroom_spores.hint", "On mycelium, podzol, or moss in the dark. Three harvests before the patch is depleted.");
        REGISTRATE.addRawLang("item.createbrewery.peyote_pup.hint", "On sand, in deserts or badlands under the sun. Very slow; the button regrows after harvesting.");
        REGISTRATE.addRawLang("createbrewery.drink.sips", "Sips: %s / %s");
        REGISTRATE.addRawLang("item.createbrewery.grape_cutting.hint", "On grass, dirt, or farmland in the sun. Once picked, the vine regrows.");
        REGISTRATE.addRawLang("item.createbrewery.agave_pup.hint", "On sand, in deserts or badlands under the sun. Very slow; dies upon harvest and yields an agave pup.");
        REGISTRATE.addRawLang("item.createbrewery.opium_poppy_seeds.hint", "On hydrated farmland in full sun.");
        REGISTRATE.addRawLang("createbrewery.dmx.console", "DMX Console");
        REGISTRATE.addRawLang("createbrewery.dmx.linked", "Fixtures linked to this console - place them around your club");
        REGISTRATE.addRawLang("createbrewery.dmx.relinked", "Fixture linked to the console");
        REGISTRATE.addRawLang("createbrewery.dmx.fixture_fan", "Fan position %s");
        REGISTRATE.addRawLang("createbrewery.dmx.effect_linked", "Linked to the console, group %s");
        REGISTRATE.addRawLang("createbrewery.dmx.too_far", "No DMX console there, or more than %s blocks away");
        REGISTRATE.addRawLang("createbrewery.dmx.lore", "Linked to DMX console at %s, %s, %s");
        REGISTRATE.addRawLang("createbrewery.dmx.fixture_status", "Group %s on the console at %s, %s, %s");
        REGISTRATE.addRawLang("createbrewery.dmx.fixture_standalone", "Group %s - no console: sound-active");
        REGISTRATE.addRawLang("createbrewery.dmx.program.manual", "Program: Manual");
        REGISTRATE.addRawLang("createbrewery.dmx.program.auto", "Program: Auto (Beat)");
        REGISTRATE.addRawLang("createbrewery.dmx.program.chase", "Program: Chase");
        REGISTRATE.addRawLang("createbrewery.dmx.move.circle", "Heads: Circle");
        REGISTRATE.addRawLang("createbrewery.dmx.move.crowd", "Heads: Crowd");
        REGISTRATE.addRawLang("createbrewery.dmx.move.straight", "Heads: Straight");
        REGISTRATE.addRawLang("createbrewery.dmx.move.fan", "Heads: Fan out");
        REGISTRATE.addRawLang("createbrewery.dmx.move.mirror", "Heads: Mirror");
        REGISTRATE.addRawLang("createbrewery.dmx.colorfx.static", "Colour: Static");
        REGISTRATE.addRawLang("createbrewery.dmx.colorfx.fade", "Colour: Fade");
        REGISTRATE.addRawLang("createbrewery.dmx.colorfx.rainbow", "Colour: Rainbow");
        REGISTRATE.addRawLang("createbrewery.dmx.colorfx.complement", "Colour: Complement");
        REGISTRATE.addRawLang("createbrewery.dmx.gobo.circle", "Gobo: Circle");
        REGISTRATE.addRawLang("createbrewery.dmx.gobo.star", "Gobo: Star");
        REGISTRATE.addRawLang("createbrewery.dmx.gobo.dots", "Gobo: Dots");
        REGISTRATE.addRawLang("createbrewery.dmx.gobo.bar", "Gobo: Bar");
        REGISTRATE.addRawLang("createbrewery.dmx.prism", "Prism: %s");
        REGISTRATE.addRawLang("createbrewery.dmx.zoom.narrow", "Zoom: Narrow");
        REGISTRATE.addRawLang("createbrewery.dmx.zoom.normal", "Zoom: Normal");
        REGISTRATE.addRawLang("createbrewery.dmx.zoom.wide", "Zoom: Wide");
        REGISTRATE.addRawLang("createbrewery.dmx.move.figure8", "Heads: Figure 8");
        REGISTRATE.addRawLang("createbrewery.dmx.move.sweep", "Heads: Sweep");
        REGISTRATE.addRawLang("createbrewery.dmx.move.ballyhoo", "Heads: Ballyhoo");
        REGISTRATE.addRawLang("createbrewery.dmx.rate", "Chase: every %s beats");
        REGISTRATE.addRawLang("createbrewery.dmx.blackout", "Blackout: %s");
        REGISTRATE.addRawLang("createbrewery.dmx.master", "Master");
        REGISTRATE.addRawLang("createbrewery.dmx.color", "Colour");
        REGISTRATE.addRawLang("createbrewery.dmx.flash", "Flash");
        REGISTRATE.addRawLang("createbrewery.dmx.scene_hint", "Click: recall scene - Shift-click: store the faders in it");
        REGISTRATE.addRawLang("createbrewery.dmx.blind_all", "BLIND");
        REGISTRATE.addRawLang("createbrewery.dmx.strobe_all", "STROBE");
        REGISTRATE.addRawLang("createbrewery.dmx.hazer", "HAZER");
        REGISTRATE.addRawLang("createbrewery.dmx.hazer_active", "Hazer: Dense haze emitted");
        REGISTRATE.addRawLang("createbrewery.dmx.fade_time", "Fade: %s");
        REGISTRATE.addRawLang("createbrewery.dmx.fade_snap", "SNAP");
        REGISTRATE.addRawLang("createbrewery.dmx.dj_sync", "DJ Sync: %s");
        REGISTRATE.addRawLang("createbrewery.dmx.tap_bpm", "TAP %s");
        REGISTRATE.addRawLang("createbrewery.dmx.gels", "Gels...");
        REGISTRATE.addRawLang("createbrewery.dmx.stage_view", "STAGE (2D)");
        REGISTRATE.addRawLang("createbrewery.dmx.page", "P%s");
        REGISTRATE.addRawLang("createbrewery.dmx.apply_all", "All Grps");
        REGISTRATE.addRawLang("createbrewery.dmx.close", "✕");
        REGISTRATE.addRawLang("createbrewery.amp.mute_tops", "Mute Tops");
        REGISTRATE.addRawLang("createbrewery.amp.mute_subs", "Mute Subs");
        REGISTRATE.addRawLang("createbrewery.amp.contour", "Bass Contour: %s");
        REGISTRATE.addRawLang("createbrewery.amp.contour.flat", "FLAT");
        REGISTRATE.addRawLang("createbrewery.amp.contour.deep", "DEEP (35Hz)");
        REGISTRATE.addRawLang("createbrewery.amp.contour.punch", "PUNCH (65Hz)");
        REGISTRATE.addRawLang("createbrewery.amp.sub_cut", "Sub-Cut: %s");
        REGISTRATE.addRawLang("createbrewery.amp.subcut.off", "OFF");
        REGISTRATE.addRawLang("createbrewery.amp.subcut.30", "30 Hz");
        REGISTRATE.addRawLang("createbrewery.amp.subcut.40", "40 Hz");
        REGISTRATE.addRawLang("createbrewery.amp.speed", "Speed: %s");
        REGISTRATE.addRawLang("createbrewery.amp.speed.on", "ON");
        REGISTRATE.addRawLang("createbrewery.amp.speed.off", "OFF");
        REGISTRATE.addRawLang("createbrewery.mic.on_standalone", "Microphone on (standalone) - right-click DJ booth with it in hand");
        REGISTRATE.addRawLang("createbrewery.dj.mixer", "DJ Mixer");
        REGISTRATE.addRawLang("createbrewery.dj.deck_a", "Deck A");
        REGISTRATE.addRawLang("createbrewery.dj.deck_b", "Deck B");
        REGISTRATE.addRawLang("createbrewery.dj.deck_c", "Deck C");
        REGISTRATE.addRawLang("createbrewery.dj.deck_d", "Deck D");
        REGISTRATE.addRawLang("createbrewery.dj.play", "▶ Play");
        REGISTRATE.addRawLang("createbrewery.dj.stop", "■ Stop");
        REGISTRATE.addRawLang("createbrewery.dj.pitch", "Pitch %s");
        REGISTRATE.addRawLang("createbrewery.dj.sync", "Sync tempo");
        REGISTRATE.addRawLang("createbrewery.dj.crossfader", "A ◀ Crossfader ▶ B");
        REGISTRATE.addRawLang("createbrewery.dj.drop", "Drop!");
        REGISTRATE.addRawLang("createbrewery.dj.autodrop", "Auto-Drop: %s");
        REGISTRATE.addRawLang("createbrewery.dj.autodrop_hint", "Automatic Drop Detection: sends redstone pulse on musical drops");
        REGISTRATE.addRawLang("createbrewery.dj.automix", "Auto-mix: %s");
        REGISTRATE.addRawLang("createbrewery.dj.eject", "Eject");
        REGISTRATE.addRawLang("createbrewery.dj.xdj_az", "AlphaTheta XDJ-AZ");
        REGISTRATE.addRawLang("createbrewery.dj.vinyl_hint", "Vinyl Mode: Scratch and pitch bend with jog wheel");
        REGISTRATE.addRawLang("createbrewery.dj.slip_hint", "Slip Mode: Track continues playing underneath scratch, loop, or reverse");
        REGISTRATE.addRawLang("createbrewery.dj.reverse_hint", "Reverse: Play track backwards");
        REGISTRATE.addRawLang("createbrewery.dj.bpm", "%s BPM");
        REGISTRATE.addRawLang("createbrewery.dj.bpm_unknown", "-- BPM");
        REGISTRATE.addRawLang("createbrewery.dj.empty", "(empty)");
        REGISTRATE.addRawLang("createbrewery.dj.cued", "%s: %s cued");
        REGISTRATE.addRawLang("createbrewery.dj.tempo_unknown", "Both decks need to play a few beats first");
        REGISTRATE.addRawLang("createbrewery.dj.out_of_range", "Tempos too far apart for the pitch fader");
        REGISTRATE.addRawLang("createbrewery.dj.synced", "%s synced to %s BPM");
        REGISTRATE.addRawLang("createbrewery.beer_tap.poured", "Fresh draft beer poured!");
        REGISTRATE.addRawLang("createbrewery.beer_tap.empty", "Beer Tap is empty!");
        REGISTRATE.addRawLang("createbrewery.beer_tap.status", "Draft Beer Tap: %s / %s mB");
        REGISTRATE.addRawLang("item.createbrewery.beer_keg", "Stainless Steel Keg");
        REGISTRATE.addRawLang("item.createbrewery.beer_mug", "Beer Mug");
        REGISTRATE.addRawLang("item.createbrewery.shot_glass", "Shot Glass");
        REGISTRATE.addRawLang("item.createbrewery.cocktail_glass", "Cocktail Glass");
        REGISTRATE.addRawLang("createbrewery.beer_tap.connected_keg", "Connected Keg: %s / %s mB");
        REGISTRATE.addRawLang("createbrewery.goggles.beer_tap.header", "Draft Beer Tap");
        REGISTRATE.addRawLang("createbrewery.goggles.beer_tap.connected_keg", "Connected Keg: %s / %s mB");
        REGISTRATE.addRawLang("createbrewery.goggles.keg.header", "Stainless Steel Keg");
        REGISTRATE.addRawLang("createbrewery.keg.empty", "The beer keg is empty.");
        REGISTRATE.addRawLang("createbrewery.keg.status", "%s: %s / %s mB");
        REGISTRATE.addRawLang("createbrewery.keg.stored_fluid", "%s: %s / %s mB");
        REGISTRATE.addRawLang("createbrewery.keg.capacity_hint", "Capacity: %s mB");
        REGISTRATE.addRawLang("createbrewery.drink.cheers_toast", "Cheers! 🍻");
        REGISTRATE.addRawLang("createbrewery.drink_glass.filled", "%s");
        REGISTRATE.addRawLang("createbrewery.drink_glass.empty_hint", "Empty - right-click beer tap or fill with bottle");
        REGISTRATE.addRawLang("createbrewery.drink_content.empty", "Empty");
        REGISTRATE.addRawLang("createbrewery.drink_content.beer", "Beer");
        REGISTRATE.addRawLang("createbrewery.drink_content.wine", "Red Wine");
        REGISTRATE.addRawLang("createbrewery.drink_content.cognac", "Cognac");
        REGISTRATE.addRawLang("createbrewery.drink_content.whiskey", "Whiskey");
        REGISTRATE.addRawLang("createbrewery.drink_content.doppelkorn", "Doppelkorn");
        REGISTRATE.addRawLang("createbrewery.drink_content.vodka", "Vodka");
        REGISTRATE.addRawLang("createbrewery.drink_content.gin", "Gin");
        REGISTRATE.addRawLang("createbrewery.drink_content.rum", "Rum");
        REGISTRATE.addRawLang("createbrewery.drink_content.tequila", "Tequila");
        REGISTRATE.addRawLang("createbrewery.drink_content.cocktail", "Cocktail");
        REGISTRATE.addRawLang("entity.createbrewery.bouncer", "Bouncer");
        REGISTRATE.addRawLang("createbrewery.ponder.first_aid.header", "First Aid");
        REGISTRATE.addRawLang("createbrewery.ponder.first_aid.text_1", "Someone is unconscious: blackout, K-hole, heart attack, or respiratory failure.");
        REGISTRATE.addRawLang("createbrewery.ponder.first_aid.text_2", "Crouch directly next to them (Sneak). As long as you stay there: CPR and recovery position keep airways clear.");
        REGISTRATE.addRawLang("createbrewery.ponder.first_aid.text_3", "Heroin: Naloxone, right-click on the victim. It only lasts about a minute - the heroin returns, so stay with them.");
        REGISTRATE.addRawLang("createbrewery.ponder.first_aid.text_4", "MDMA and overheating: shade, rest, electrolyte drink instead of chugging plain water.");
        REGISTRATE.addRawLang("createbrewery.ponder.first_aid.text_5", "Never use alone. Never mix: alcohol with heroin, Xanax, or ketamine halts breathing.");
        com.createbrewery.drugs.DrugInfo.addLang();
        REGISTRATE.addRawLang("createbrewery.ponder.fermenter.header", "Fermenting Beer in the Fermenter");
        REGISTRATE.addRawLang("createbrewery.ponder.fermenter.text_1", "The Fermenter turns Hopped Wort and Yeast into Beer over time.");
        REGISTRATE.addRawLang("createbrewery.ponder.fermenter.text_2", "Unlike most Create machines, the Fermenter requires NO shaft or rotational force. It is completely passive.");
        REGISTRATE.addRawLang("createbrewery.ponder.fermenter.text_3", "Hopped Wort can be piped into the Fermenter from any side.");
        REGISTRATE.addRawLang("createbrewery.ponder.fermenter.text_4", "Yeast can be inserted with a Funnel or by hand.");
        REGISTRATE.addRawLang("createbrewery.ponder.fermenter.text_5", "Engineer's Goggles display fermentation progress.");
        REGISTRATE.addRawLang("createbrewery.ponder.fermenter.text_6", "Fermenting: 20% (0.8 days remaining)");
        REGISTRATE.addRawLang("createbrewery.ponder.fermenter.text_7", "Fermenting: 60% (0.4 days remaining)");
        REGISTRATE.addRawLang("createbrewery.ponder.fermenter.text_8", "Fermenting: 100% (Ready)");
        REGISTRATE.addRawLang("createbrewery.ponder.fermenter.text_9", "Finished Beer can then be piped out and bottled.");
        REGISTRATE.addRawLang("createbrewery.ponder.brewing_heat.header", "Brewing Heat Requirements");
        REGISTRATE.addRawLang("createbrewery.ponder.brewing_heat.text_1", "Brewing requires different heat tiers for different stages of the process.");
        REGISTRATE.addRawLang("createbrewery.ponder.brewing_heat.text_2", "Mashing (Grist + Water -> Wort) requires standard HEAT (Kindled Blaze Burner).");
        REGISTRATE.addRawLang("createbrewery.ponder.brewing_heat.text_3", "Boiling (Wort + Hops -> Hopped Wort) requires SUPERHEATED heat (fed with Blaze Cake).");
        REGISTRATE.addRawLang("createbrewery.ponder.brewing_heat.text_4", "Remember: Mashing needs standard heat, while Boiling hops must be Superheated!");
        // The "Apotheke" advancement tab: JSON in data/createbrewery/advancement/drugs.
        // advancements:begin
        advancement("root", "Apotheke", "Take any drug");
        advancement("bier", "After-Work Beer", "Drink a beer");
        advancement("joint", "Roll One First", "Take a drag from a joint");
        advancement("greening_out", "Greening Out", "Smoke so much your blood pressure collapses");
        advancement("koks", "Nose Powder", "Snort a line of cocaine");
        advancement("herzrasen", "Thump Thump Thump", "Send your heart racing");
        advancement("herzinfarkt", "That Was Too Much", "Suffer a heart attack");
        advancement("zweites_leben", "Second Chance", "Survive a heart attack");
        advancement("keta", "Horse Tranquilizer", "Snort a line of ketamine");
        advancement("k_loch", "Welcome to the K-Hole", "Take enough ketamine to fall into the K-hole");
        advancement("ck", "Snow and Horses", "Have cocaine and ketamine in your system simultaneously");
        advancement("ibu", "Cures Everything", "Take an ibuprofen");
        advancement("lsd", "Colors Make Sounds Now", "Place an LSD blotter on your tongue");
        advancement("ego_tod", "Ego Death", "Reach the peak of a heroic dose of LSD");
        advancement("pilze", "Fun Guy", "Eat a magic mushroom");
        advancement("heldendosis", "Heroic Dose", "Eat three magic mushrooms and stay still in the dark");
        advancement("meskalin", "Desert Prophet", "Chew a peyote cactus button");
        advancement("purga", "La Purga", "Experience the cleansing catharsis of a peyote trip");
        advancement("pforten", "Doors of Perception", "Experience the is-ness of a peyote trip in the desert");
        advancement("horrortrip", "Bad Set, Bad Setting", "Spiral into a bad trip");
        advancement("dmt", "Through the Curtain", "Smoke DMT");
        advancement("maschinenelfen", "Hello Machine Elves", "Break through into hyperspace and meet its inhabitants");
        advancement("mdma", "Hug Everybody", "Take an ecstasy pill");
        advancement("hitzschlag", "Water, Water!", "Overheat while dancing on ecstasy");
        advancement("kuschelmonster", "Cuddle Monster", "Hug a creeper while on ecstasy (sneak up close)");
        advancement("meth", "Say My Name", "Smoke crystal meth");
        advancement("psychose", "Shadow People", "Stay awake on crystal meth until you see things");
        advancement("heroin", "Don't Nod Off", "Shoot up heroin");
        advancement("atemstillstand", "Breathe!", "Take enough that your breathing stops");
        advancement("entzug", "Monkey on Your Back", "Go through withdrawal");
        advancement("xanax", "Nothing Matters", "Take a Xanax");
        advancement("lachgas", "Wah Wah", "Inhale a nitrous balloon");
        advancement("candyflip", "Candyflip", "Drop ecstasy while on a trip");
        advancement("dehydriert", "Parched", "Drink alcohol on ecstasy");
        advancement("speedball", "Speedball", "Mix heroin with cocaine or crystal meth");
        advancement("nachgelegt", "Doubled Down", "Smoke weed while tripping");
        advancement("gipfelsturm", "Peak Storming", "Inhale nitrous oxide while tripping");
        advancement("apotheke_leer", "Cabinet Cleaned Out", "Take every drug at least once");
        // advancements:end
        if (net.neoforged.fml.loading.FMLEnvironment.dist.isClient()) {
            modEventBus.addListener(CreateBreweryClient::onClientSetup);
            modEventBus.addListener(com.createbrewery.drunk.DrunkClient::onRegisterClientExtensions);
            modEventBus.addListener(com.createbrewery.drunk.DrunkClient::addLayers);
            modEventBus.addListener(com.createbrewery.drunk.DrunkClient::registerRenderers);
            modEventBus.addListener(com.createbrewery.drunk.DrunkClient::registerLayerDefinitions);
            modEventBus.addListener(com.createbrewery.particle.BreweryParticle::register);
            modEventBus.addListener(com.createbrewery.particle.FogParticle::registerShaders);
        }
        ModRecipeTypes.register(modEventBus);
        modEventBus.addListener(com.createbrewery.drugs.DrugPose::register);
        modEventBus.addListener(com.createbrewery.drugs.DrugDebug::register);
        modEventBus.addListener(com.createbrewery.block.club.DjControl::register);
        modEventBus.addListener(com.createbrewery.block.club.DmxControl::register);
        modEventBus.addListener(com.createbrewery.block.club.AmpControl::register);
        modEventBus.addListener(ModRecipeProvider::gatherData);
        ModLootModifiers.register(modEventBus);
        ModDataMaps.register(modEventBus);
        ModVillagerTrades.register();
        net.neoforged.neoforge.common.NeoForge.EVENT_BUS.register(com.createbrewery.event.BreweryCommonEvents.class);
        net.neoforged.neoforge.common.NeoForge.EVENT_BUS.register(com.createbrewery.drunk.DrunkServer.class);
        net.neoforged.neoforge.common.NeoForge.EVENT_BUS.register(com.createbrewery.drugs.DrugServer.class);
        modContainer.registerConfig(ModConfig.Type.COMMON, Config.SPEC);
        modContainer.registerConfig(ModConfig.Type.CLIENT, Config.CLIENT_SPEC);
    }

    private static void advancement(String path, String title, String description) {
        REGISTRATE.addRawLang("advancements.createbrewery.drugs." + path + ".title", title);
        REGISTRATE.addRawLang("advancements.createbrewery.drugs." + path + ".description", description);
    }

    public static ResourceLocation ID(String path) {
        return ResourceLocation.fromNamespaceAndPath(MOD_ID, path);
    }
}
